rails_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :todos do
    member do
      patch :complete
    end
  end
end

rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_app/app/models/todo.rb
class Todo < ApplicationRecord
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails_app/app/controllers/todos_controller.rb
require 'add_todo/interactor'
require 'delete_todo/interactor'
require 'complete_todo/interactor'
require 'list_todos/interactor'
require 'todo_overview/presenter'

class TodosController < ApplicationController

  def index
    todos = ListTodos::Interactor.new(repository).execute
    @view_model = TodoOverview::Presenter.new(todos).build_view_model
  end

  def create
    AddTodo::Interactor.new(repository).execute(params[:title])
    redirect_to todos_path
  end

  def destroy
    DeleteTodo::Interactor.new(repository).execute(params[:title])
    redirect_to todos_path
  end

  def complete
    CompleteTodo::Interactor.new(repository).execute(params[:title])
    redirect_to todos_path
  end

  private

  def repository
    TodoRepository.new
  end

end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_app/app/views/todos/index.html.erb
<h1>Todos</h1>

<ul>
  <% @view_model.todos.each do |todo| %>
    <li>
      <% if todo.striked? %>
        <strike><%= todo.title %></strike>
      <% else %>
        <%= todo.title %>
      <% end %>
      
      <% if todo.deletable? %>
        <%= form_tag todo_path(todo), method: :delete, style: "display: inline-block" do %>
          <%= hidden_field_tag :title, todo.title %>
          <%= button_tag 'x' %>
        <% end %>
      <% end %>

      <% if todo.completable? %>
        <%= form_tag complete_todo_path(todo), method: :patch, style: "display: inline-block" do %>
          <%= hidden_field_tag :title, todo.title %>
          <%= button_tag '✔' %>
        <% end %>
      <% end %>

    </li>
  <% end %>
</ul>

<%= form_tag todos_path, method: :post do %>
  <%= text_field_tag :title %>
  <%= button_tag @view_model.add_button_text %>
<% end %>